log4perl-init:
  class: Log::Log4perl
  method: init
  args:
    - $ref: log4perl-configurator

log4perl-configurator:
  class: Log::Log4perl::Config::YamlConfigurator
  args:
    data: 
      $ref: log4perl-configurator-data

log4perl-configurator-data:
  value:
    rootLogger: INFO, SCREEN
    category:
      Foo:
        Bar:
          name: DEBUG, SCREEN, FILE
          Baz: INFO, FILE
    additivity:
      Foo:
        Bar: 0
    appender:
      SCREEN: 
        name: Log::Log4perl::Appender::Screen
        layout: Log::Log4perl::Layout::SimpleLayout
      FILE: 
        name: Log::Log4perl::Appender::File
        filename: file.log
        mode: append
        create_at_logtime: 1
        layout:
          name: Log::Log4perl::Layout::PatternLayout::Multiline
          ConversionPattern: '%d{HH:mm:ss} %-5p [%M{3}, %L] - %m%n'
