name: CI

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  test:
    uses: XSven/github_workflows/.github/workflows/cpan-test.yml@main
    with:
      perl_version: "[ '5.14.4' ]"
