name: CI

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  test:
    uses: XSven/github_workflows/.github/workflows/cpan-test.yml@development
    with:
      perl_version: '[ "5.14.4" ]'
      testing_context: '[ "release" ]'
