name: CI

on:
  workflow_dispatch:
    branches: [ development ]

jobs:
  test:
    uses: PerlToolsTeam/github_workflows/.github/workflows/cpan-test.yml@main
    with:
      perl_version: "[ 'latest' ]"
